import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050505',
  },

  mapStage: {
    flex: 1,
    backgroundColor: '#050505',
  },
  mapTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(3, 8, 12, 0.05)',
  },

  topRow: {
    position: 'absolute',
    left: 16,
    right: 16,
    zIndex: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButtonFloating: {
    minHeight: 42,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: 'rgba(8, 12, 16, 0.48)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: {width: 0, height: 4},
    elevation: 8,
  },
  backButtonIcon: {
    marginRight: 3,
  },
  backButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },

  bellButton: {
    width: 50,
    height: 50,
    borderRadius: 16,
    backgroundColor: 'rgba(8, 12, 16, 0.48)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: {width: 0, height: 4},
    elevation: 8,
  },
  bellBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    minWidth: 20,
    height: 20,
    paddingHorizontal: 4,
    borderRadius: 10,
    backgroundColor: '#FF4D4F',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#101418',
  },
  bellBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
  },

  statsRail: {
    position: 'absolute',
    left: 16,
    zIndex: 20,
  },
  statPill: {
    width: 98,
    minHeight: 62,
    marginBottom: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderRadius: 16,
    backgroundColor: 'rgba(8, 12, 16, 0.48)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: {width: 0, height: 4},
    elevation: 8,
  },
  statAccent: {
    width: 22,
    height: 3,
    borderRadius: 999,
    marginBottom: 6,
    alignSelf: 'center',
  },
  speedAccent: {
    backgroundColor: '#59C3C3',
  },
  distanceAccent: {
    backgroundColor: '#FFB703',
  },
  timeAccent: {
    backgroundColor: '#FF6B52',
  },
  ascentAccent: {
    backgroundColor: '#7AE582',
  },
  statPillLabel: {
    color: '#C9D2DB',
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 0.8,
    marginBottom: 4,
    textAlign: 'center',
  },
  statValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  statPillValue: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
    lineHeight: 16,
    textAlign: 'center',
  },
  statPillUnit: {
    color: '#DCE3EA',
    fontSize: 8,
    fontWeight: '700',
    marginLeft: 3,
    marginBottom: 1,
  },

  importantNotificationCard: {
    position: 'absolute',
    left: 16,
    right: 16,
    zIndex: 21,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderWidth: 1,
    shadowColor: '#000000',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: {width: 0, height: 4},
    elevation: 8,
  },
  importantNotificationWarning: {
    backgroundColor: 'rgba(20, 24, 30, 0.52)',
    borderColor: 'rgba(255, 183, 3, 0.22)',
  },
  importantNotificationDanger: {
    backgroundColor: 'rgba(36, 14, 16, 0.58)',
    borderColor: 'rgba(255, 82, 82, 0.28)',
  },
  importantNotificationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  importantNotificationTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 10,
  },
  importantNotificationIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(255,255,255,0.10)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  importantNotificationTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    flex: 1,
  },
  importantNotificationBadge: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
  },
  importantNotificationBadgeWarning: {
    backgroundColor: 'rgba(255, 183, 3, 0.12)',
    borderColor: 'rgba(255, 183, 3, 0.28)',
  },
  importantNotificationBadgeDanger: {
    backgroundColor: 'rgba(255, 82, 82, 0.12)',
    borderColor: 'rgba(255, 82, 82, 0.28)',
  },
  importantNotificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  importantNotificationMessage: {
    color: '#E5E7EB',
    fontSize: 12,
    lineHeight: 17,
  },

  actionRowFloating: {
    position: 'absolute',
    left: 16,
    right: 16,
    zIndex: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  actionButton: {
    flex: 1,
    minHeight: 66,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: {width: 0, height: 6},
    elevation: 10,
  },
  actionButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonIcon: {
    marginRight: 7,
  },
  actionButtonText: {
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  pauseButton: {
    marginRight: 7,
    backgroundColor: '#F7A508',
  },
  pauseButtonText: {
    color: '#111111',
  },
  resumeButton: {
    marginRight: 7,
    backgroundColor: '#1C9B5F',
  },
  resumeButtonText: {
    color: '#FFFFFF',
  },
  disabledActionButton: {
    marginRight: 7,
    backgroundColor: 'rgba(44, 52, 61, 0.86)',
  },
  disabledActionButtonText: {
    color: '#D1D5DB',
  },
  finishButton: {
    marginLeft: 7,
    backgroundColor: '#F44336',
  },
  finishButtonText: {
    color: '#FFFFFF',
  },

  notificationsOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 60,
    backgroundColor: 'rgba(0,0,0,0.30)',
  },
  notificationsOverlayTouch: {
    flex: 1,
  },

  notificationsPanel: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    zIndex: 61,
    backgroundColor: 'rgba(12, 15, 20, 0.94)',
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 16,
    shadowColor: '#000000',
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: {width: -6, height: 0},
    elevation: 14,
  },
  notificationsHandle: {
    alignSelf: 'center',
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.16)',
    marginBottom: 14,
  },
  notificationsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  notificationsTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 3,
  },
  notificationsSubtitle: {
    color: '#9AA5B1',
    fontSize: 12,
  },
  notificationsCloseButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationsScroll: {
    flex: 1,
  },
  notificationItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.04)',
    marginBottom: 12,
  },
  notificationIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 107, 82, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  notificationTextWrap: {
    flex: 1,
  },
  notificationTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  notificationItemTitle: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    marginRight: 8,
  },
  notificationItemTime: {
    color: '#93A0AD',
    fontSize: 11,
    fontWeight: '700',
  },
  notificationItemMessage: {
    color: '#C2CAD4',
    fontSize: 12,
    lineHeight: 18,
  },
  notificationUnreadDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#FF6B52',
    marginTop: 5,
    marginLeft: 8,
  },

  summaryBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.62)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  summaryCard: {
    width: '100%',
    backgroundColor: '#111111',
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: '#1F1F1F',
  },
  summaryTitle: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 18,
    textAlign: 'center',
  },
  summaryMetrics: {
    marginBottom: 22,
  },
  summaryMetric: {
    backgroundColor: '#181818',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 12,
  },
  summaryLabel: {
    color: '#A9A9A9',
    fontSize: 13,
    marginBottom: 6,
  },
  summaryValue: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
  },
  summaryActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  summaryButton: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryButtonSecondary: {
    backgroundColor: '#242424',
    marginRight: 6,
  },
  summaryButtonPrimary: {
    backgroundColor: '#FF6B52',
    marginLeft: 6,
  },
  summaryButtonSecondaryText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  summaryButtonPrimaryText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  weatherAccent: {
    backgroundColor: '#59C3C3',
  },

  statMiniText: {
    color: '#BFC7D1',
    fontSize: 8,
    fontWeight: '700',
    marginTop: 3,
    textAlign: 'center',
  },
});