import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050505',
  },
  topBar: {
    position: 'absolute',
    left: 18,
    right: 18,
    zIndex: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  backButton: {
    minHeight: 48,
    paddingHorizontal: 14,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(20, 22, 24, 0.78)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    shadowColor: '#000000',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  backButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  notificationButton: {
    width: 54,
    height: 54,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(20, 22, 24, 0.78)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    shadowColor: '#000000',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  notificationBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    paddingHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF3B30',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  notificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
  },
  metricsRail: {
    position: 'absolute',
    left: 18,
    zIndex: 12,
    gap: 10,
  },
  metricCard: {
    width: 96,
    minHeight: 72,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(28, 31, 34, 0.78)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.10)',
    shadowColor: '#000000',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
  },
  metricAccent: {
    width: 24,
    height: 3,
    borderRadius: 3,
    marginBottom: 6,
  },
  metricAccentSpeed: {
    backgroundColor: '#4DD8D8',
  },
  metricAccentDistance: {
    backgroundColor: '#FFB000',
  },
  metricAccentTime: {
    backgroundColor: '#FF6B52',
  },
  metricAccentAscent: {
    backgroundColor: '#62E57C',
  },
  metricAccentWeather: {
    backgroundColor: '#4DD8D8',
  },
  metricLabel: {
    color: 'rgba(255, 255, 255, 0.68)',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  metricValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginTop: 2,
    gap: 3,
  },
  metricValue: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  metricUnit: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '800',
    marginBottom: 2,
  },
  weatherMetricCard: {
    backgroundColor: 'rgba(18, 21, 24, 0.86)',
  },
  weatherMetricValue: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '900',
    marginTop: 2,
  },
  weatherMetricDetail: {
    color: 'rgba(255, 255, 255, 0.70)',
    fontSize: 9,
    fontWeight: '800',
    marginTop: 2,
  },
  floatingWarning: {
    position: 'absolute',
    left: 18,
    right: 18,
    top: 122,
    zIndex: 30,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255, 59, 48, 0.88)',
  },
  floatingWarningText: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  bottomControls: {
    position: 'absolute',
    left: 18,
    right: 18,
    zIndex: 20,
    flexDirection: 'row',
    gap: 14,
  },
  controlButton: {
    flex: 1,
    minHeight: 66,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    shadowColor: '#000000',
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 10,
  },
  controlButtonPressed: {
    opacity: 0.62,
    transform: [{scale: 0.98}],
  },
  pauseButton: {
    backgroundColor: '#FFAA00',
  },
  pauseButtonText: {
    color: '#111111',
    fontSize: 15,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  finishButton: {
    backgroundColor: '#FF443A',
  },
  finishButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  notificationLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 60,
  },
  notificationOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.42)',
  },
  notificationOverlayPressable: {
    flex: 1,
  },
  notificationsPanel: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 18,
    paddingBottom: 22,
    backgroundColor: 'rgba(10, 10, 10, 0.96)',
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(255, 255, 255, 0.10)',
  },
  notificationsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  notificationsTitle: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '900',
  },
  notificationsSubtitle: {
    color: 'rgba(255, 255, 255, 0.58)',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 2,
  },
  notificationsCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  notificationItem: {
    flexDirection: 'row',
    gap: 12,
    padding: 14,
    borderRadius: 18,
    marginBottom: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  notificationItemIcon: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF6B52',
  },
  notificationItemContent: {
    flex: 1,
  },
  notificationItemTitle: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  notificationItemMessage: {
    color: 'rgba(255, 255, 255, 0.66)',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
    marginTop: 3,
  },
  modalBackdrop: {
    flex: 1,
    paddingHorizontal: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.66)',
  },
  confirmModalCard: {
    width: '100%',
    maxWidth: 360,
    padding: 22,
    borderRadius: 28,
    alignItems: 'center',
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 82, 0.42)',
  },
  confirmModalIcon: {
    width: 58,
    height: 58,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF6B52',
    marginBottom: 14,
  },
  confirmModalTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
  },
  confirmModalText: {
    color: 'rgba(255, 255, 255, 0.68)',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    textAlign: 'center',
    marginTop: 10,
  },
  confirmModalActions: {
    width: '100%',
    flexDirection: 'row',
    gap: 12,
    marginTop: 22,
  },
  confirmModalButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmModalButtonSecondary: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.10)',
  },
  confirmModalButtonPrimary: {
    backgroundColor: '#FF443A',
  },
  confirmModalButtonSecondaryText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  confirmModalButtonPrimaryText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  summaryCard: {
    width: '100%',
    maxWidth: 370,
    padding: 22,
    borderRadius: 30,
    alignItems: 'center',
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 82, 0.40)',
  },
  summaryIcon: {
    width: 58,
    height: 58,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF6B52',
    marginBottom: 14,
  },
  summaryTitle: {
    color: '#FFFFFF',
    fontSize: 23,
    fontWeight: '900',
    textAlign: 'center',
  },
  summarySubtitle: {
    color: 'rgba(255, 255, 255, 0.62)',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 5,
    textAlign: 'center',
  },
  summaryGrid: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 20,
  },
  summaryItem: {
    width: '48%',
    padding: 12,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  summaryItemWide: {
    width: '100%',
  },
  summaryLabel: {
    color: 'rgba(255, 255, 255, 0.58)',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  summaryValue: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
    marginTop: 4,
  },
  summaryButton: {
    width: '100%',
    minHeight: 54,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF6B52',
    marginTop: 20,
  },
  summaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
});
