import {Dimensions, StyleSheet} from 'react-native';

const {width} = Dimensions.get('window');

export const palette = {
  bg: '#060708',
  card: '#121315',
  cardSoft: '#181A1E',
  border: 'rgba(255,255,255,0.10)',
  borderStrong: 'rgba(255,255,255,0.18)',
  text: '#FFFFFF',
  textMuted: 'rgba(255,255,255,0.62)',
  textSoft: 'rgba(255,255,255,0.38)',
  accent: '#FF5B4B',
  accentDark: '#B7372E',
  gold: '#E8A020',
};

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.bg,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 34,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 18,
  },
  iconButton: {
    width: 50,
    height: 50,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: palette.border,
  },
  iconButtonText: {
    color: palette.text,
    fontSize: 42,
    lineHeight: 45,
    marginTop: -4,
  },
  headerCopy: {
    flex: 1,
    alignItems: 'center',
  },
  title: {
    color: palette.text,
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: -0.7,
    textAlign: 'center',
  },
  subtitle: {
    color: palette.textMuted,
    fontSize: 14,
    marginTop: 5,
    textAlign: 'center',
  },
  diceButton: {
    width: 50,
    height: 50,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,91,75,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255,91,75,0.34)',
  },
  diceText: {
    color: palette.accent,
    fontSize: 24,
    fontWeight: '900',
  },
  previewCard: {
    minHeight: 285,
    borderRadius: 28,
    backgroundColor: '#111214',
    borderWidth: 1,
    borderColor: 'rgba(255,91,75,0.34)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 16,
  },
  previewGlow: {
    position: 'absolute',
    width: 210,
    height: 210,
    borderRadius: 105,
    bottom: -58,
    backgroundColor: 'rgba(255,91,75,0.18)',
  },
  gridFloor: {
    position: 'absolute',
    left: -20,
    right: -20,
    bottom: 0,
    height: 92,
    borderTopWidth: 1,
    borderColor: 'rgba(255,91,75,0.18)',
    backgroundColor: 'rgba(255,91,75,0.025)',
  },
  previewActions: {
    position: 'absolute',
    right: 14,
    top: 62,
    gap: 12,
  },
  previewActionButton: {
    width: 72,
    height: 68,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: palette.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewActionIcon: {
    color: palette.text,
    fontSize: 25,
    fontWeight: '900',
  },
  previewActionText: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
  },
  bodyTypeCard: {
    borderRadius: 24,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 14,
    marginBottom: 16,
    flexDirection: width > 370 ? 'row' : 'column',
    justifyContent: 'space-between',
    alignItems: width > 370 ? 'center' : 'stretch',
    gap: 14,
  },
  sectionOverline: {
    color: palette.accent,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 2,
  },
  bodyToggleGroup: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 18,
    padding: 4,
    gap: 4,
  },
  bodyToggle: {
    flex: 1,
    minWidth: 112,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  bodyToggleActive: {
    backgroundColor: 'rgba(255,91,75,0.18)',
    borderColor: palette.accent,
  },
  bodyToggleText: {
    color: palette.textMuted,
    fontSize: 14,
    fontWeight: '800',
  },
  bodyToggleTextActive: {
    color: palette.text,
  },
  editorCard: {
    borderRadius: 28,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.border,
    overflow: 'hidden',
  },
  categoryTabs: {
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 8,
    gap: 8,
  },
  categoryTab: {
    width: 92,
    minHeight: 78,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  categoryTabActive: {
    borderColor: palette.accent,
    backgroundColor: 'rgba(255,91,75,0.13)',
  },
  categoryIcon: {
    color: palette.textSoft,
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 5,
  },
  categoryIconActive: {
    color: palette.accent,
  },
  categoryLabel: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  categoryLabelActive: {
    color: palette.accent,
  },
  editorSection: {
    borderTopWidth: 1,
    borderTopColor: palette.border,
    padding: 14,
  },
  editorTitle: {
    color: palette.text,
    fontSize: 17,
    fontWeight: '900',
    marginBottom: 12,
  },
  optionList: {
    gap: 10,
    paddingRight: 4,
  },
  optionTile: {
    width: 96,
    height: 126,
    borderRadius: 18,
    backgroundColor: palette.cardSoft,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 4,
  },
  optionTileActive: {
    borderColor: palette.accent,
    backgroundColor: 'rgba(255,91,75,0.13)',
  },
  optionLabel: {
    position: 'absolute',
    bottom: 10,
    left: 6,
    right: 6,
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
  },
  optionLabelActive: {
    color: palette.text,
  },
  checkBadge: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 22,
    height: 22,
    borderRadius: 11,
    color: palette.text,
    backgroundColor: palette.accent,
    textAlign: 'center',
    lineHeight: 22,
    fontSize: 13,
    fontWeight: '900',
    overflow: 'hidden',
  },
  colorList: {
    gap: 12,
    paddingRight: 4,
  },
  colorButton: {
    width: 50,
    height: 50,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  colorButtonActive: {
    borderColor: palette.accent,
    borderWidth: 2,
  },
  colorSwatch: {
    width: 36,
    height: 36,
    borderRadius: 12,
  },
  colorCheck: {
    position: 'absolute',
    color: palette.text,
    fontSize: 18,
    fontWeight: '900',
    textShadowColor: 'rgba(0,0,0,0.60)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 4,
  },
  facingGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  facingTile: {
    width: '47.9%',
    minHeight: 134,
    borderRadius: 20,
    backgroundColor: palette.cardSoft,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  facingTileActive: {
    borderColor: palette.accent,
    backgroundColor: 'rgba(255,91,75,0.10)',
  },
  facingLabel: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '800',
    marginTop: -2,
  },
  facingLabelActive: {
    color: palette.text,
  },
  saveButton: {
    height: 62,
    borderRadius: 20,
    backgroundColor: palette.accent,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 18,
    shadowColor: palette.accent,
    shadowOffset: {width: 0, height: 12},
    shadowOpacity: 0.28,
    shadowRadius: 18,
    elevation: 8,
  },
  saveButtonText: {
    color: palette.text,
    fontSize: 18,
    fontWeight: '900',
  },
});
